server.port=8080
spring.thymeleaf.cache=false
spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html

# Security login page
server.error.whitelabel.enabled=false
logging.level.org.springframework.security=INFO

app.quiz.rotationSeconds=20
app.quiz.maxPlayers=13
